[package]
name = "cdg_renderer"
version = "0.2.0"
authors = ["TQ Hirsch <thequux@thequux.com>"]
description = "CD+G renderer"
repository = "https://github.com/thequux/qaraoke"
license = "ISC"

keywords = ["cdg", "karaoke"]


[dependencies]
cdg = { path = "../cdg", version= "0.1" }
image = "0.21"
