[package]
authors = ["TQ Hirsch <thequux@thequux.com>"]
name = "ogk"
version = "0.1.0"

[dependencies]
bitflags = "0.7.0"
byteorder = "0.5.3"
cdg = "0.1"
crc = "1.3.0"
lazy_static = "0.2.1"
lz4 = "1.18"
ogg-sys = "0.0.9"
rand = "0.3.14"
